# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Audiomixaudio(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, input_file_1: str=None, input_file_2: str=None, output_file: str=None):  # noqa: E501
        """Audiomixaudio - a model defined in Swagger

        :param input_file_1: The input_file_1 of this Audiomixaudio.  # noqa: E501
        :type input_file_1: str
        :param input_file_2: The input_file_2 of this Audiomixaudio.  # noqa: E501
        :type input_file_2: str
        :param output_file: The output_file of this Audiomixaudio.  # noqa: E501
        :type output_file: str
        """
        self.swagger_types = {
            'input_file_1': str,
            'input_file_2': str,
            'output_file': str
        }

        self.attribute_map = {
            'input_file_1': 'input_file_1',
            'input_file_2': 'input_file_2',
            'output_file': 'output_file'
        }
        self._input_file_1 = input_file_1
        self._input_file_2 = input_file_2
        self._output_file = output_file

    @classmethod
    def from_dict(cls, dikt) -> 'Audiomixaudio':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The audiomixaudio of this Audiomixaudio.  # noqa: E501
        :rtype: Audiomixaudio
        """
        return util.deserialize_model(dikt, cls)

    @property
    def input_file_1(self) -> str:
        """Gets the input_file_1 of this Audiomixaudio.

        Choose an audio file:  # noqa: E501

        :return: The input_file_1 of this Audiomixaudio.
        :rtype: str
        """
        return self._input_file_1

    @input_file_1.setter
    def input_file_1(self, input_file_1: str):
        """Sets the input_file_1 of this Audiomixaudio.

        Choose an audio file:  # noqa: E501

        :param input_file_1: The input_file_1 of this Audiomixaudio.
        :type input_file_1: str
        """
        if input_file_1 is None:
            raise ValueError("Invalid value for `input_file_1`, must not be `None`")  # noqa: E501

        self._input_file_1 = input_file_1

    @property
    def input_file_2(self) -> str:
        """Gets the input_file_2 of this Audiomixaudio.

        Choose another audio file:  # noqa: E501

        :return: The input_file_2 of this Audiomixaudio.
        :rtype: str
        """
        return self._input_file_2

    @input_file_2.setter
    def input_file_2(self, input_file_2: str):
        """Sets the input_file_2 of this Audiomixaudio.

        Choose another audio file:  # noqa: E501

        :param input_file_2: The input_file_2 of this Audiomixaudio.
        :type input_file_2: str
        """
        if input_file_2 is None:
            raise ValueError("Invalid value for `input_file_2`, must not be `None`")  # noqa: E501

        self._input_file_2 = input_file_2

    @property
    def output_file(self) -> str:
        """Gets the output_file of this Audiomixaudio.

        Choose the output format:  # noqa: E501

        :return: The output_file of this Audiomixaudio.
        :rtype: str
        """
        return self._output_file

    @output_file.setter
    def output_file(self, output_file: str):
        """Sets the output_file of this Audiomixaudio.

        Choose the output format:  # noqa: E501

        :param output_file: The output_file of this Audiomixaudio.
        :type output_file: str
        """
        allowed_values = ["mp3", "wav", "ogg", "flac", "wma"]  # noqa: E501
        if output_file not in allowed_values:
            raise ValueError(
                "Invalid value for `output_file` ({0}), must be one of {1}"
                .format(output_file, allowed_values)
            )

        self._output_file = output_file
