# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Imageresize(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, input_file: str=None, output_file: str=None, new_size: str=None):  # noqa: E501
        """Imageresize - a model defined in Swagger

        :param input_file: The input_file of this Imageresize.  # noqa: E501
        :type input_file: str
        :param output_file: The output_file of this Imageresize.  # noqa: E501
        :type output_file: str
        :param new_size: The new_size of this Imageresize.  # noqa: E501
        :type new_size: str
        """
        self.swagger_types = {
            'input_file': str,
            'output_file': str,
            'new_size': str
        }

        self.attribute_map = {
            'input_file': 'input_file',
            'output_file': 'output_file',
            'new_size': 'new_size'
        }
        self._input_file = input_file
        self._output_file = output_file
        self._new_size = new_size

    @classmethod
    def from_dict(cls, dikt) -> 'Imageresize':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The imageresize of this Imageresize.  # noqa: E501
        :rtype: Imageresize
        """
        return util.deserialize_model(dikt, cls)

    @property
    def input_file(self) -> str:
        """Gets the input_file of this Imageresize.

        Choose the image to resize:  # noqa: E501

        :return: The input_file of this Imageresize.
        :rtype: str
        """
        return self._input_file

    @input_file.setter
    def input_file(self, input_file: str):
        """Sets the input_file of this Imageresize.

        Choose the image to resize:  # noqa: E501

        :param input_file: The input_file of this Imageresize.
        :type input_file: str
        """
        if input_file is None:
            raise ValueError("Invalid value for `input_file`, must not be `None`")  # noqa: E501

        self._input_file = input_file

    @property
    def output_file(self) -> str:
        """Gets the output_file of this Imageresize.

        Choose the output format:  # noqa: E501

        :return: The output_file of this Imageresize.
        :rtype: str
        """
        return self._output_file

    @output_file.setter
    def output_file(self, output_file: str):
        """Sets the output_file of this Imageresize.

        Choose the output format:  # noqa: E501

        :param output_file: The output_file of this Imageresize.
        :type output_file: str
        """
        allowed_values = ["jpg", "png", "gif", "bmp", "tiff"]  # noqa: E501
        if output_file not in allowed_values:
            raise ValueError(
                "Invalid value for `output_file` ({0}), must be one of {1}"
                .format(output_file, allowed_values)
            )

        self._output_file = output_file

    @property
    def new_size(self) -> str:
        """Gets the new_size of this Imageresize.

        Specify the new size <i>(Percentage: 25 or size 640x480)</i>:  # noqa: E501

        :return: The new_size of this Imageresize.
        :rtype: str
        """
        return self._new_size

    @new_size.setter
    def new_size(self, new_size: str):
        """Sets the new_size of this Imageresize.

        Specify the new size <i>(Percentage: 25 or size 640x480)</i>:  # noqa: E501

        :param new_size: The new_size of this Imageresize.
        :type new_size: str
        """
        if new_size is None:
            raise ValueError("Invalid value for `new_size`, must not be `None`")  # noqa: E501

        self._new_size = new_size
