# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Imagerotate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, input_file: str=None, output_file: str=None, grades: str=None):  # noqa: E501
        """Imagerotate - a model defined in Swagger

        :param input_file: The input_file of this Imagerotate.  # noqa: E501
        :type input_file: str
        :param output_file: The output_file of this Imagerotate.  # noqa: E501
        :type output_file: str
        :param grades: The grades of this Imagerotate.  # noqa: E501
        :type grades: str
        """
        self.swagger_types = {
            'input_file': str,
            'output_file': str,
            'grades': str
        }

        self.attribute_map = {
            'input_file': 'input_file',
            'output_file': 'output_file',
            'grades': 'grades'
        }
        self._input_file = input_file
        self._output_file = output_file
        self._grades = grades

    @classmethod
    def from_dict(cls, dikt) -> 'Imagerotate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The imagerotate of this Imagerotate.  # noqa: E501
        :rtype: Imagerotate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def input_file(self) -> str:
        """Gets the input_file of this Imagerotate.

        Choose the image to rotate:  # noqa: E501

        :return: The input_file of this Imagerotate.
        :rtype: str
        """
        return self._input_file

    @input_file.setter
    def input_file(self, input_file: str):
        """Sets the input_file of this Imagerotate.

        Choose the image to rotate:  # noqa: E501

        :param input_file: The input_file of this Imagerotate.
        :type input_file: str
        """
        if input_file is None:
            raise ValueError("Invalid value for `input_file`, must not be `None`")  # noqa: E501

        self._input_file = input_file

    @property
    def output_file(self) -> str:
        """Gets the output_file of this Imagerotate.

        Choose the output format:  # noqa: E501

        :return: The output_file of this Imagerotate.
        :rtype: str
        """
        return self._output_file

    @output_file.setter
    def output_file(self, output_file: str):
        """Sets the output_file of this Imagerotate.

        Choose the output format:  # noqa: E501

        :param output_file: The output_file of this Imagerotate.
        :type output_file: str
        """
        allowed_values = ["jpg", "png", "gif", "bmp", "tiff"]  # noqa: E501
        if output_file not in allowed_values:
            raise ValueError(
                "Invalid value for `output_file` ({0}), must be one of {1}"
                .format(output_file, allowed_values)
            )

        self._output_file = output_file

    @property
    def grades(self) -> str:
        """Gets the grades of this Imagerotate.

        Specify the number of degrees to rotate:  # noqa: E501

        :return: The grades of this Imagerotate.
        :rtype: str
        """
        return self._grades

    @grades.setter
    def grades(self, grades: str):
        """Sets the grades of this Imagerotate.

        Specify the number of degrees to rotate:  # noqa: E501

        :param grades: The grades of this Imagerotate.
        :type grades: str
        """
        if grades is None:
            raise ValueError("Invalid value for `grades`, must not be `None`")  # noqa: E501

        self._grades = grades
