# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Metadatageter(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, input_file: str=None):  # noqa: E501
        """Metadatageter - a model defined in Swagger

        :param input_file: The input_file of this Metadatageter.  # noqa: E501
        :type input_file: str
        """
        self.swagger_types = {
            'input_file': str
        }

        self.attribute_map = {
            'input_file': 'input_file'
        }
        self._input_file = input_file

    @classmethod
    def from_dict(cls, dikt) -> 'Metadatageter':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The metadatageter of this Metadatageter.  # noqa: E501
        :rtype: Metadatageter
        """
        return util.deserialize_model(dikt, cls)

    @property
    def input_file(self) -> str:
        """Gets the input_file of this Metadatageter.


        :return: The input_file of this Metadatageter.
        :rtype: str
        """
        return self._input_file

    @input_file.setter
    def input_file(self, input_file: str):
        """Sets the input_file of this Metadatageter.


        :param input_file: The input_file of this Metadatageter.
        :type input_file: str
        """
        if input_file is None:
            raise ValueError("Invalid value for `input_file`, must not be `None`")  # noqa: E501

        self._input_file = input_file
