# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Videotoimages(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, input_file: str=None, output_file: str=None, fps: str=None):  # noqa: E501
        """Videotoimages - a model defined in Swagger

        :param input_file: The input_file of this Videotoimages.  # noqa: E501
        :type input_file: str
        :param output_file: The output_file of this Videotoimages.  # noqa: E501
        :type output_file: str
        :param fps: The fps of this Videotoimages.  # noqa: E501
        :type fps: str
        """
        self.swagger_types = {
            'input_file': str,
            'output_file': str,
            'fps': str
        }

        self.attribute_map = {
            'input_file': 'input_file',
            'output_file': 'output_file',
            'fps': 'fps'
        }
        self._input_file = input_file
        self._output_file = output_file
        self._fps = fps

    @classmethod
    def from_dict(cls, dikt) -> 'Videotoimages':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The videotoimages of this Videotoimages.  # noqa: E501
        :rtype: Videotoimages
        """
        return util.deserialize_model(dikt, cls)

    @property
    def input_file(self) -> str:
        """Gets the input_file of this Videotoimages.

        Choose the video to convert:  # noqa: E501

        :return: The input_file of this Videotoimages.
        :rtype: str
        """
        return self._input_file

    @input_file.setter
    def input_file(self, input_file: str):
        """Sets the input_file of this Videotoimages.

        Choose the video to convert:  # noqa: E501

        :param input_file: The input_file of this Videotoimages.
        :type input_file: str
        """
        if input_file is None:
            raise ValueError("Invalid value for `input_file`, must not be `None`")  # noqa: E501

        self._input_file = input_file

    @property
    def output_file(self) -> str:
        """Gets the output_file of this Videotoimages.

        Choose the output format:  # noqa: E501

        :return: The output_file of this Videotoimages.
        :rtype: str
        """
        return self._output_file

    @output_file.setter
    def output_file(self, output_file: str):
        """Sets the output_file of this Videotoimages.

        Choose the output format:  # noqa: E501

        :param output_file: The output_file of this Videotoimages.
        :type output_file: str
        """
        allowed_values = ["jpg", "png", "gif", "bmp", "tiff"]  # noqa: E501
        if output_file not in allowed_values:
            raise ValueError(
                "Invalid value for `output_file` ({0}), must be one of {1}"
                .format(output_file, allowed_values)
            )

        self._output_file = output_file

    @property
    def fps(self) -> str:
        """Gets the fps of this Videotoimages.

        Specify the number of images per second <i>(Recommended: 1)</i>:  # noqa: E501

        :return: The fps of this Videotoimages.
        :rtype: str
        """
        return self._fps

    @fps.setter
    def fps(self, fps: str):
        """Sets the fps of this Videotoimages.

        Specify the number of images per second <i>(Recommended: 1)</i>:  # noqa: E501

        :param fps: The fps of this Videotoimages.
        :type fps: str
        """
        if fps is None:
            raise ValueError("Invalid value for `fps`, must not be `None`")  # noqa: E501

        self._fps = fps
